swagger: "2.0"
info:
  description: Documentation for the API for the chemical transformation database
  version: "1.0.0"
  title: Chemical Transformation API
consumes:
  - application/json
produces:
  - applications/json

basePath: /api

paths:
  /author:
    get:
      operationId: operations.author.get
      tags:
        - Author
      summary: Retrieves all data from the author table
      description: Retrieves all data from the author table
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                  description: Primary key of the record
                first_name:
                  type: string
                  description: First name of the author
                middle_name:
                  type: string
                  description: Middle name of the author
                last_name:
                  type: string
                  description: Last name of the author